name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Phonebook
        run: gcc -Wall -Wextra -Werror -O2 "Phonebook.c" -o phonebook.exe

      - name: Build Movie Management System
        run: gcc -Wall -Wextra -Werror -O2 "Movie Management System.c" -o movie_management.exe
